/* Authoritative public eligibility references. These are catalog records for
   official web sources, not copied or synthetic policy content. Authors import
   a source into Open Notebook before it can enter the artifact workflow. */
const eligibilityLibraryWebSources = [
  {
    id: "web:tx-texas-works-handbook",
    title: "Texas Works Handbook",
    jurisdiction: "Texas",
    owner: "Texas Health and Human Services",
    document_type: "policy_manual",
    programs: ["SNAP", "TANF", "Medicaid"],
    format: "Web manual",
    effective_date: "Current web edition",
    status: "Official web source",
    url: "https://fhb.hhs.texas.gov/handbooks/texas-works-handbook",
    description: "Policies and procedures used to determine eligibility for SNAP, TANF, and medical programs for families and children."
  },
  {
    id: "web:tx-mepd-handbook",
    title: "Medicaid for the Elderly and People with Disabilities Handbook",
    jurisdiction: "Texas",
    owner: "Texas Health and Human Services",
    document_type: "policy_manual",
    programs: ["Medicaid"],
    format: "Web manual",
    effective_date: "Current web edition",
    status: "Official web source",
    url: "https://fhb.hhs.texas.gov/handbooks/medicaid-elderly-people-disabilities-handbook",
    description: "Eligibility policy and procedures for Medicaid programs serving older adults and people with disabilities."
  },
  {
    id: "web:tx-b6500-denials",
    title: "B-6500 — Denials and Missing Information Procedures",
    jurisdiction: "Texas",
    owner: "Texas Health and Human Services",
    document_type: "sop_procedure",
    programs: ["Medicaid"],
    format: "Web procedure",
    effective_date: "Current web edition",
    status: "Official web source",
    url: "https://fhb.hhs.texas.gov/handbooks/medicaid-elderly-people-disabilities-handbook/b-6500-denials",
    description: "Operational procedure for verification requests, pending periods, redeterminations, and application denials."
  },
  {
    id: "web:tx-h1200-application",
    title: "Form H1200 — Application for Assistance",
    jurisdiction: "Texas",
    owner: "Texas Health and Human Services",
    document_type: "application_form",
    programs: ["Medicaid"],
    format: "Form / PDF",
    effective_date: "Current form edition",
    status: "Official web source",
    url: "https://fhb.hhs.texas.gov/forms/1000-1999/form-h1200-application-assistance-your-texas-benefits",
    description: "Application source used for Medicaid for older adults, people with disabilities, and related assistance."
  },
  {
    id: "web:tx-mepd-revision-26-2",
    title: "MEPD Handbook Revision 26-2",
    jurisdiction: "Texas",
    owner: "Texas Health and Human Services",
    document_type: "policy_bulletin",
    programs: ["Medicaid"],
    format: "Web revision notice",
    effective_date: "June 1, 2026",
    status: "Official web source",
    url: "https://fhb.hhs.texas.gov/handbooks/medicaid-elderly-people-disabilities-handbook/26-2-june-quarterly-revision",
    description: "Current quarterly revision notice for the MEPD Handbook, including incorporated 2026 policy bulletins and revised eligibility reference sections."
  },
  {
    id: "web:mi-bridges-manuals",
    title: "Michigan Bridges Policy Manuals",
    jurisdiction: "Michigan",
    owner: "Michigan Department of Health and Human Services",
    document_type: "policy_manual",
    programs: ["SNAP", "TANF", "Medicaid"],
    format: "Web manual collection",
    effective_date: "Current web edition",
    status: "Official web source",
    url: "https://mdhhs-pres-prod.michigan.gov/OLMWeb/exF/html/index.html",
    description: "Bridges Eligibility Manual, Bridges Administrative Manual, reference tables, schedules, glossaries, and update bulletins."
  },
  {
    id: "web:mi-assistance-application",
    title: "MDHHS-1171 — Assistance Application",
    jurisdiction: "Michigan",
    owner: "Michigan Department of Health and Human Services",
    document_type: "application_form",
    programs: ["SNAP", "TANF", "Medicaid"],
    format: "Application packet",
    effective_date: "Current form edition",
    status: "Official web source",
    url: "https://www.michigan.gov/mdhhs/assistance-programs/emergency-relief/forms-pubs/forms/assistance-application-mdhhs-1171",
    description: "Application packet with information booklet, filing form, and program-specific supplements."
  },
  {
    id: "web:mi-client-questions-qrg",
    title: "Quick Reference Guide — Answering Common Client Questions",
    jurisdiction: "Michigan",
    owner: "Michigan Department of Health and Human Services",
    document_type: "job_aid",
    programs: ["Integrated eligibility"],
    format: "PDF quick reference",
    effective_date: "Current posted edition",
    status: "Official web source",
    url: "https://www.michigan.gov/mdhhs/-/media/Project/Websites/mdhhs/Doing-Business-with-MDHHS/MI-Bridges-Partners/Community_Partner-Answering_Clients_Questions.pdf",
    description: "A client-question quick reference for MI Bridges community partners."
  },
  {
    id: "web:mi-policy-letters-forms",
    title: "Medicaid Policy, Letters and Forms",
    jurisdiction: "Michigan",
    owner: "Michigan Department of Health and Human Services",
    document_type: "policy_bulletin",
    programs: ["Medicaid"],
    format: "Web collection",
    effective_date: "Continuously updated",
    status: "Official web source",
    url: "https://www.michigan.gov/mdhhs/assistance-programs/medicaid/portalhome/medicaid-providers/policyforms/policy-letters-and-forms",
    description: "Current and proposed policy bulletins, numbered letters, eligibility policy manuals, and forms."
  },
  {
    id: "web:mi-continuous-eligibility-bulletin",
    title: "MMP 23-73 — Continuous Eligibility for Children",
    jurisdiction: "Michigan",
    owner: "Michigan Department of Health and Human Services",
    document_type: "policy_bulletin",
    programs: ["Medicaid", "CHIP"],
    format: "PDF bulletin",
    effective_date: "January 1, 2024",
    status: "Official web source",
    url: "https://www.michigan.gov/mdhhs/-/media/Project/Websites/mdhhs/Assistance-Programs/Medicaid-BPHASA/Public-Comment/2347-Eligibility-P.pdf",
    description: "Policy-change bulletin for continuous eligibility for Medicaid and MIChild beneficiaries under age 19."
  },
  {
    id: "web:az-cnap-manual",
    title: "Cash and Nutrition Assistance Policy Manual",
    jurisdiction: "Arizona",
    owner: "Arizona Department of Economic Security",
    document_type: "policy_manual",
    programs: ["SNAP", "TANF"],
    format: "Web manual",
    effective_date: "Current web edition",
    status: "Official web source",
    url: "https://dbmefaapolicy.azdes.gov/How_To_Use_This_Manual/Customer_Info.html",
    description: "Family Assistance Administration policy for Arizona Cash and Nutrition Assistance programs."
  },
  {
    id: "web:az-ahcccs-epm",
    title: "AHCCCS Medical Assistance Eligibility Policy Manual",
    jurisdiction: "Arizona",
    owner: "Arizona Health Care Cost Containment System",
    document_type: "policy_manual",
    programs: ["Medicaid", "CHIP"],
    format: "Web manual",
    effective_date: "Current web edition",
    status: "Official web source",
    url: "https://epm.azahcccs.gov/EligibilityPolicyManual/Policy/Chapter_100_AHCCCS_Medical_Assistance/Introduction.htm",
    description: "Eligibility policy, definitions, and legal authorities for Arizona medical assistance programs."
  },
  {
    id: "web:az-faa-0001a",
    title: "FAA-0001A — Application for Benefits",
    jurisdiction: "Arizona",
    owner: "Arizona DES and AHCCCS",
    document_type: "application_form",
    programs: ["SNAP", "TANF", "Medicaid"],
    format: "PDF application",
    effective_date: "February 2026",
    status: "Official web source",
    url: "https://des.az.gov/sites/default/files/dl/FAA-0001A.pdf",
    description: "Integrated application for Nutrition Assistance, Cash Assistance, and AHCCCS medical coverage."
  },
  {
    id: "web:az-faa-0412a",
    title: "FAA-0412A — Change Report",
    jurisdiction: "Arizona",
    owner: "Arizona Department of Economic Security",
    document_type: "application_form",
    programs: ["SNAP", "TANF", "Medicaid"],
    format: "PDF form",
    effective_date: "April 2026",
    status: "Official web source",
    url: "https://des.az.gov/sites/default/files/dl/FAA-0412A.pdf",
    description: "Household change-report form with program-specific reporting guidance."
  },
  {
    id: "web:az-how-to-apply",
    title: "How to Apply for Nutrition Assistance",
    jurisdiction: "Arizona",
    owner: "Arizona Department of Economic Security",
    document_type: "training_outreach",
    programs: ["SNAP"],
    format: "Web guide and video",
    effective_date: "Current web edition",
    status: "Official web source",
    url: "https://des.az.gov/node/10274",
    description: "Client-facing application guidance, preparation information, and how-to videos, including Spanish and ASL resources."
  }
];
